---
- hosts: raspberry-pi
  sudo: false
  vars:
    deb_dir: "/home/pi/debs"
#    node_js_url: "http://node-arm.herokuapp.com/node_0.10.36_armhf.deb"
    node_js_url: "http://node-arm.herokuapp.com/node_latest_armhf.deb"
#    node_js_deb_file: "node_0.10.36-1_armhf.deb"
    node_js_deb_file: "node_latest_armhf.deb"
    ble_scanner_repo: "https://github.com/c0ze/node-ble-beacon-scanner"
    ble_scanner_dir: "/home/pi/ble-scanner"
  tasks:
    - name: Make download dir
      sudo: false
      file: path={{ deb_dir }} state=directory
    - name: Download Node Js
      sudo: false
      get_url: url={{ node_js_url }} dest={{ deb_dir }}
    - name: Install Node js
      sudo: true
      action: shell cd {{ deb_dir }} && dpkg -i {{ node_js_deb_file }}
    - name: Install Ble Beacon Scanner
      sudo: false
      git: repo={{ ble_scanner_repo }}
           dest={{ ble_scanner_dir }}
    - name: Install apt dependencies
      sudo: true
      apt: name={{ item }} state=present
      with_items:
        - bluetooth
        - bluez-utils
        - libbluetooth-dev
    - name: Install npm dependencies
      sudo: false
      npm: path={{ ble_scanner_dir }} state=present
    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=latest

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Start ble beacon scan Node.js app."
      command: forever start "{{ ble_scanner_dir }}/app.js"
      when: "forever_list.stdout.find('{{ ble_scanner_dir }}/app.js') == -1"